name: Continuous Integration

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

env:
  NODE_VERSION: '20'

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create test environment
        run: |
          cat > .env << EOF
          API_BASE_URL=https://api.test.com/v1
          API_SIGNUP_URL=https://api.test.com/v1/api
          API_ACTIVATION_URL=https://api.test.com/v1/api/activated
          API_AUTHENTICATION_URL=https://api.test.com/v1/api/authentication
          MUSIC_API_NEWS_URL=https://api.test.com/v1/musical/news
          MUSIC_API_TRENDS_URL=https://api.test.com/v1/musical/trends
          MUSIC_API_LYRICS_URL=https://api.test.com/v1/musical/lyrics
          MUSIC_API_TRACK_INFO_URL=https://api.test.com/v1/musical/track-info
          MUSIC_API_HEALTH_URL=https://api.test.com/v1/health
          VITE_API_BASE_URL=https://api.test.com/v1
          VITE_API_SIGNUP_URL=https://api.test.com/v1/api
          VITE_API_ACTIVATION_URL=https://api.test.com/v1/api/activated
          VITE_API_AUTHENTICATION_URL=https://api.test.com/v1/api/authentication
          VITE_MUSIC_API_NEWS_URL=https://api.test.com/v1/musical/news
          VITE_MUSIC_API_TRENDS_URL=https://api.test.com/v1/musical/trends
          VITE_MUSIC_API_LYRICS_URL=https://api.test.com/v1/musical/lyrics
          VITE_MUSIC_API_TRACK_INFO_URL=https://api.test.com/v1/musical/track-info
          VITE_MUSIC_API_HEALTH_URL=https://api.test.com/v1/health
          VITE_APP_NAME="Musical Zoe"
          VITE_APP_VERSION="1.0.0"
          VITE_APP_ENV="test"
          EOF

      - name: Run linting
        run: npm run lint

      - name: Run type checking
        run: npm run check

      - name: Run tests
        run: npm test

      - name: Build application
        run: npm run build

      - name: Run security audit
        run: npm audit --audit-level high
        continue-on-error: true
